
# Make and Makefiles

## Make and Makefiles

- Make is an automated build system, designed to avoid costly
  recomputation.

- `make` examines a *Makefile*, which contains a set of rules describing
  dependencies among files.

- A rule is run (i.e the recipes are executed) if the *target* is older than 
  any of its *dependencies* (*prerequisites*). 

```
target: prerequisites ...
     recipe
     ...
```

- `make` works backwards from the target to the prerequisites and
  compares creation time of files (`timestamp`).

## Make and Makefile

- Example:

```
res.txt: param1.dat param2.dat
         simulation param1.dat param2.dat > res1.dat
         post-process res1.dat > res.txt
```

- Commands to be run should be indented with a TAB.


## A complete Makefile 

See the `rr_make` directory.

```
report.pdf: report.tex sim1.pdf sim2.pdf 
	texi2pdf report.tex

sim1.dat: params.r simulator.r
	rscript simulator.r rnorm > sim1.dat

sim2.dat: params.r simulator.r
	rscript simulator.r runif > sim2.dat

sim1.pdf: sim1.dat plotter.r
	rscript plotter.r sim1.dat

sim2.pdf: sim2.dat plotter.r
	rscript plotter.r sim2.dat


.phony: all clean

all: report.pdf

clean:
	rm -f report.pdf report.log report.aux
	rm -f sim1.* sim2*
```


## Graphical description of dependencies

![./figures/makedep.pdf]

** Makefile conventions

   - PHONY targets: denote actions; ignore filenames with same
     name. PHONY targets are always out of date, and so always run.

#+begin_src example
.PHONY: all clean
all: report.pdf

clean:
	rm -f report.pdf report.log report.aux
	rm -f sim1.* sim2*

#+end_src

        |------------+---------------------------------------|
        | command    | action                                |
        |------------+---------------------------------------|
        | make       | check first rule                      |
        | make all   | rebuild everything                    |
        | make clean | remove files that can be rebuilt      |
        | touch file | update timestamp, preserving contents |
        |------------+---------------------------------------|


** Makefile: next steps

- variables
- implicit rules
- saving space:
: sim2.dat: params.R simulator.R
:	Rscript simulator.R runif > sim2.dat

: sim2.dat: params.R simulation.R
:	Rscript simulator.R runif > $@

- parallel processing =make -j2 job=

** Makefile references

- Further reading: 
[[http://linuxdevcenter.com/pub/a/linux/2002/01/31/make_intro.html][http://linuxdevcenter.com/pub/a/linux/2002/01/31/make_intro.html]]

- Managing Projects with GNU Make 
[[http://oreilly.com/catalog/make3/book/index.csp][http://oreilly.com/catalog/make3/book/index.csp]]

- The GNU make manual 
[[http://www.gnu.org/software/make/manual/make.html][http://www.gnu.org/software/make/manual/make.html]]

** Makefile: example lab work

- In the lab session, download =rr_make.zip=
\note{stored in directory \url{rr_make}}

- Experiment with remaking report after changing parameters.

- Add a new plot to the report, using sim3 -- sampling N numbers from
  rgamma with new parameters (stored in params.R).  You will need to
  edit simulator.R too.

* Sweave

** Sweave: literate programming for R

   - Sweave is the system for mixing \LaTeX and \R code in the same
     document.

   - Used within \R often to create "vignettes" which can be
     dynamically run.

   - Allows you to write reports where results (tables, graphs) are
     automatically generated by your \R code.

** Sweave: including code chunks
   
- An example code chunk: by default we are in 'LaTeX mode'.

#+begin_src example
We can then test the procedure a few
times, using the default number 
of darts, 1000:

<<>>=
replicate(9, estimate.pi())
@ 
#+end_src

** Sweave: including graphs

- Automatically creates filenames, e.g. ~estimate-001.pdf~

- By default will generate .ps and .pdf; so change options:
: \SweaveOpts{echo=TRUE,pdf=TRUE,eps=FALSE,eval=TRUE,keep.source=TRUE}

#+begin_src example
\setkeys{Gin}{width=0.6\textwidth}
\begin{center}
<<fig=TRUE>>=
r <- 1; n <- 50; par(las=1)
plot(NA, xlim=c(-r,r), ylim=c(-r,r), asp=1, bty='n',
     xaxt='n', yaxt='n', xlab='', ylab='')
axis(1, at=c(-r,0,r)); axis(2, at=c(-r,0,r))
symbols(x=0, y=0, circles=r, inch=F, add=T)
...
rect(-r, -r, r, r, border='blue', lwd=2)
@ 
\end{center}
#+end_src


** Sweave: including tables

- Use the /xtable/ package from CRAN.  

- Example from that package:


#+begin_src example
<<echo=FALSE>>=
library(xtable)
data(tli)
@ 

<<label=tab1,echo=FALSE,results=tex>>=
     ## Demonstrate data.frame
     tli.table <- xtable(tli[1:20,])
     digits(tli.table)[c(2,6)] <- 0
     print(tli.table)
@ 
#+end_src example

** Sweave: including inline computation

#+begin_src example
In this case the number of darts within
the circle is \Sexpr{d}, and so the estimated
value is $\pi \approx \Sexpr{4*d/n}$.
#+end_src

** Sweave: a full example
   - Example application: estimate the value of \pi using the
   dartboard method. 
   - [[estimate.Rnw][estimate.Rnw]]

   - See handout of estimate.Rnw and estimate.pdf

   - For nice ways to customize Sweave output
   [[http://proteome.sysbiol.cam.ac.uk/lgatto/teaching/files/Sweave-customisation.pdf][http://proteome.sysbiol.cam.ac.uk/lgatto/teaching/files/Sweave-customisation.pdf]]
   - Compiling the document with make:
   
#+begin_src example
estimate.pdf: estimate.Rnw
	R CMD Sweave estimate.Rnw
	pdflatex estimate.tex
#+end_src

** Sweave: issues and next steps.

- If you edit \texttt{.tex}, Sweave code is re-run.  Compare with Makefiles,
  which offer finer-level control.

- Tedious to keep running with long calculations.  
  =cacheSweave= package will help to cache results.

- FAQ available:
#+LaTeX: \url{http://www.stat.uni-muenchen.de/~leisch/Sweave/FAQ.htm}

- /odfWeave/ and /RHTML/ packages allow for output to OpenOffice and
  HTML.

- matrices and data frames can be export, e.g. using =xtable= package.

* Other approaches to RR

** Other approaches to RR

- \R packages: truly reproducible research.  \R packages allow you to
  include code, data, documentation, vignettes.

- The \R package =ascii=[fn:ascii] allows you to embed \R code into your
    documents.

# http://www.ncfaculty.net/dogle/fishR/bookex/AIFFD/AIFFD_Main.html

- *Org mode*[fn:orgm] and *Org babel*[fn:orgb]: Only Emacs users need apply.  Key advantage: allows many
  different languages to be included in one document, with textual
  communication between those programs. Org mode exports to multiple formats. \\
  (show source of these slides)

- =knitr= is an alternative to =Sweave=, that uses caching, syntax highlighting, 
  code tidy-up, ... by default. Also weaves to html. Good integration with =rstudio=.

[fn:ascii] [[http://eusebe.github.com/ascii][http://eusebe.github.com/ascii]]
[fn:orgm] [[http://orgmode.org/][http://orgmode.org/]]
[fn:orgb] [[http://orgmode.org/worg/org-contrib/babel/][http://orgmode.org/worg/org-contrib/babel/]]


** Extra handouts
   1. Makefile: report.pdf
   2. Sweave: =estimate.Rnw= and =estimate.pdf= 
   3. Using =kntir=: =estimatek.Rnw= and =estimatek.pdf= 

Available at 
- [[http://proteome.sysbiol.cam.ac.uk/lgatto/teaching/files/estimate.zip][http://proteome.sysbiol.cam.ac.uk/lgatto/teaching/files/estimate.zip]] 
- [[http://proteome.sysbiol.cam.ac.uk/lgatto/teaching/files/rr_make.zip][http://proteome.sysbiol.cam.ac.uk/lgatto/teaching/files/rr_make.zip]]
and 
#+LaTex: \url{pwf:~/COMPBIO/spr/practicals/}
